//use this variable during developing to limit vertexes generated by circles 
//should be power of 2
develop_mode=1;

epsilon=0.001;

xs_fn=max(4,8/develop_mode);
s_fn=max(4,16/develop_mode);
m_fn=max(4,32/develop_mode);
l_fn=max(4,64/develop_mode);
xl_fn=max(4,128/develop_mode);

screw_hook=[
  26,//screw hooks distance
  6, //screw hook hole y-offset
];
srhk=screw_hook;
